### ISSUE TITLE
Loot Distribution Showing Improper Results/No Results [Bug]

### ISSUE THREAD

**Issue by krutticus** [Alumian/CEPGP-Retail#265] opened 2020-06-15 13:02 UTC
**The Error**
No error message is received

**Describe the bug**
As an officer with access to officer notes and with raid assist, when I bring up the loot distribution to see responses coming in it will only display a small portion of the raid's responses.  Of the responses that do show, some are incorrect or not listed at all.  This is happening to multiple of our officer/raid assists.  This has been happening for about a month now and does not seem to be affecting our Loot Master.  I've tried resyncing settings with our Loot Master and a fresh reinstall of the addon but neither have fixed the issue.  I did not take a screencap, but will in the next raid and update.

**To Reproduce**
I am unable to tell what is causing the issue to replicate.  It happens every loot distribution.

**Debug Information**
<details><summary>Debug Info</summary><br />
Version: 1.12.16 Release<br />
Locale: enUS<br />
Poll Rate: 0.0001<br />
GP Formula: (9x(2^<sup>((ilvl/26)+(rarity-4))</sup>)xSlot Modifier)x1<br />
Base GP: 101<br />
Traffic Entries: 1608<br />
Base GP Decay Factor: false<br />
Standby EP: True<br />
Standby Offline: True<br />
Standby Percent: 25<br />
Standby Accept Whispers: True<br />
Standby EP by Rank: False<br />
Standby EP Manual Delegation: True<br />
Standby EP Whisper Keyphrase: standby<br />
Auto Pass on Ineligible Items: false<br />
Full Raid Loot Visibility: false<br />
GP on Tooltips: true<br />
Suppress Loot Announcements: true<br />
Roll for Passes: false<br />
Announce Rolls: true<br />
Resolve Duplicate Rolls: true<br />
Minimum EP: false, 0<br />
Reporting Channel: Raid<br />
Loot Response Channel: Raid<br />
Minimum Threshold for Loot: 4<br />
Allow Force Sync: false, Guild Master<br />
Hide Keyphrase Alternatives: True<br /><br /><details><summary>Auto EP</summary>
High Priestess Jeklik: True<br />
Gothik the Harvester: True<br />
Buru the Gorger: True<br />
Wushoolay: True<br />
Silithid Royalty: True<br />
Ossirian the Unscarred: True<br />
Golemagg the Incinerator: True<br />
Grand Widow Faerlina: True<br />
High Priestess Mar'li: True<br />
Twin Emperors: True<br />
Majordomo Executus: True<br />
High Priest Venoxis: True<br />
Gehennas: True<br />
Taerar: True<br />
Ysondre: True<br />
Thane Korth'azz: True<br />
High Priest Thekal: True<br />
Noth the Plaguebringer: True<br />
Lethon: True<br />
Moam: True<br />
The Prophet Skeram: True<br />
Flamegor: True<br />
C'Thun: True<br />
General Rajaxx: True<br />
The Edge of Madness: True<br />
Princess Huhuran: True<br />
Thaddius: True<br />
Loatheb: True<br />
The Silithid Royalty: True<br />
Ayamiss the Hunter: True<br />
Ebonroc: True<br />
Gluth: True<br />
Heigan the Unclean: True<br />
Onyxia: True<br />
Doom Lord Kazzak: True<br />
Sulfuron Harbinger: True<br />
Baron Geddon: True<br />
High Priestess Arlokk: True<br />
Gri'lek: True<br />
Sapphiron: True<br />
Chromaggus: True<br />
Firemaw: True<br />
Viscidus: True<br />
Azuregos: True<br />
Bloodlord Mandokir: True<br />
Razorgore the Untamed: True<br />
Shazzrah: True<br />
The Twin Emperors: True<br />
Battleguard Sartura: True<br />
Gahz'ranka: True<br />
Kel'Thuzad: True<br />
Nefarian: True<br />
Fankriss the Unyielding: True<br />
Lucifron: True<br />
Anub'Rekhan: True<br />
Hazza'rah: True<br />
Ouro: True<br />
Ragnaros: True<br />
Maexxna: True<br />
Hakkar: True<br />
Broodlord Lashlayer: True<br />
The Four Horsemen: True<br />
Kurinnaxx: True<br />
Grobbulus: True<br />
Instructor Razuvious: True<br />
Emeriss: True<br />
Magmadar: True<br />
Patchwerk: True<br />
Vaelastrasz the Corrupt: True<br />
Renataki: True<br />
Jin'do the Hexxer: True<br />
Garr: True<br />
</details>
<details><summary>EP Values</summary>
High Priestess Jeklik: 2<br />
Gothik the Harvester: 12<br />
Buru the Gorger: 3<br />
Wushoolay: 2<br />
Silithid Royalty: 10<br />
Ossirian the Unscarred: 4<br />
Golemagg the Incinerator: 10<br />
Grand Widow Faerlina: 12<br />
High Priestess Mar'li: 2<br />
Twin Emperors: 10<br />
Majordomo Executus: 10<br />
High Priest Venoxis: 2<br />
Gehennas: 10<br />
Taerar: 7<br />
Ysondre: 7<br />
Thane Korth'azz: 15<br />
High Priest Thekal: 2<br />
Noth the Plaguebringer: 12<br />
Lethon: 7<br />
Moam: 3<br />
The Prophet Skeram: 10<br />
Flamegor: 20<br />
C'Thun: 12<br />
General Rajaxx: 3<br />
The Edge of Madness: 2<br />
Princess Huhuran: 10<br />
Thaddius: 15<br />
Loatheb: 15<br />
The Silithid Royalty: 10<br />
Ayamiss the Hunter: 3<br />
Ebonroc: 20<br />
Gluth: 12<br />
Heigan the Unclean: 12<br />
Onyxia: 15<br />
Doom Lord Kazzak: 7<br />
Sulfuron Harbinger: 10<br />
Baron Geddon: 10<br />
High Priestess Arlokk: 2<br />
Gri'lek: 2<br />
Sapphiron: 15<br />
Chromaggus: 20<br />
Firemaw: 20<br />
Viscidus: 10<br />
Azuregos: 7<br />
Bloodlord Mandokir: 2<br />
Razorgore the Untamed: 20<br />
Shazzrah: 10<br />
The Twin Emperors: 10<br />
Battleguard Sartura: 10<br />
Gahz'ranka: 2<br />
Kel'Thuzad: 15<br />
Nefarian: 20<br />
Fankriss the Unyielding: 10<br />
Lucifron: 10<br />
Anub'Rekhan: 12<br />
Hazza'rah: 2<br />
Ouro: 10<br />
Ragnaros: 15<br />
Maexxna: 15<br />
Hakkar: 3<br />
Broodlord Lashlayer: 20<br />
The Four Horsemen: 15<br />
Kurinnaxx: 3<br />
Grobbulus: 12<br />
Instructor Razuvious: 12<br />
Emeriss: 7<br />
Magmadar: 10<br />
Patchwerk: 12<br />
Vaelastrasz the Corrupt: 20<br />
Renataki: 2<br />
Jin'do the Hexxer: 2<br />
Garr: 10<br />
</details>
<details><summary>Loot Button Configuration</summary>
Loot Button 1<br />State: Enabled<br />Button Text: Need<br />Discount: 0%<br />Keyphrase Alternative: Need<br /><br />Loot Button 2<br />State: Enabled<br />Button Text: Greed<br />Discount: 50%<br />Keyphrase Alternative: Greed<br /><br />Loot Button 3<br />State: Enabled<br />Button Text: Offspec<br />Discount: 100%<br />Keyphrase Alternative: Offspec<br /><br />Loot Button 4<br />State: Enabled<br />Button Text: Alt Roll<br />Discount: 80%<br />Keyphrase Alternative: Alt<br /><br /></details><details><summary>Standby Guild Ranks</summary>
Guild Master: False<br />
Guild Master: False<br />
Raid Leader: False<br />
Officer: False<br />
Officer Alt: False<br />
Raider: False<br />
Veteran: False<br />
Member: False<br />
Initiate: False<br />
</details>
<details><summary>Slot Weights</summary>
2HWEAPON: 1.5<br />
NECK: 1<br />
HEAD: 1<br />
WEAPON: 1.5<br />
WRIST: 0.5<br />
WEAPONMAINHAND: 1.5<br />
SHIELD: 0.5<br />
HOLDABLE: 0.5<br />
CLOAK: 0.5<br />
SHOULDER: 0.75<br />
FEET: 0.75<br />
RANGED: 0.5<br />
FINGER: 1<br />
WAIST: 0.75<br />
TRINKET: 0.75<br />
WAND: 0.5<br />
LEGS: 1<br />
HAND: 0.75<br />
ROBE: 1<br />
CHEST: 1<br />
WEAPONOFFHAND: 0.75<br />
EXCEPTION: 1<br />
RELIC: 0.5<br />
THROWN: 0.5<br />
</details>
<details><summary>Override List</summary>
</details>
<details><summary>Addons List</summary>
AngryAssignments<br />
Atlas<br />
Atlas_ClassicWoW<br />
AtlasLootClassic<br />
Auc-Advanced<br />
Auc-Filter-Basic<br />
Auc-Stat-Histogram<br />
Auc-Stat-iLevel<br />
Auc-Stat-Purchased<br />
Auc-Stat-Simple<br />
Auc-Stat-StdDev<br />
Auc-Util-FixAH<br />
BeanCounter<br />
BiSTracker<br />
CEPGP<br />
CEPGP_Data<br />
ClassicHealingAssignments<br />
Classic Quest Log<br />
Decursive<br />
Details<br />
Details_Streamer<br />
Details_TinyThreat<br />
Enchantrix-Barker<br />
ExtendedCharacterStats<br />
FarmLog<br />
GatherMate2<br />
GTFO<br />
ItemRack<br />
NovaWorldBuffs<br />
Peggle<br />
RCLootCouncil_Classic<br />
SexyMap<br />
SlideBar<br />
Spy<br />
Stubby<br />
!Swatter<br />
ThreatClassic2<br />
TitanClassicAmmo<br />
TitanClassicBag<br />
TitanClassicClock<br />
TitanClassicGold<br />
TitanClassicLocation<br />
TitanClassicLootType<br />
TitanClassicPerformance<br />
TitanClassicRegen<br />
TitanClassicRepair<br />
TitanClassicVolume<br />
TitanClassicXP<br />
TitanClassic<br />
VendorPrice<br />
WeakAuras<br />
CharacterStatsClassic<br />
TradeSkillMaster<br />
TradeSkillMaster_AppHelper<br />
ElvUI<br />
DBM-Core<br />
DBM-DefaultSkin<br />
DBM-StatusBarTimers<br />
Questie<br />
</details>
<details><summary>Enabled Plugins</summary>
</details>
</details>

**Comment by Alumian** [comment] 2020-06-15 13:12
To my understanding, this is caused by Blizzard throttling addon messages (an undocumented change). This is extremely inconsistent and I haven't been able to discern any noticeable pattern.
I'll continue to investigate and I hope that Blizzard rolls back their changes soon.

**Comment by krutticus** [comment] 2020-06-15 13:34
Thanks for getting back to me so quickly.  This completely makes sense and I recall seeing you callout the undocumented change in the changelog.

**Comment by Alumian** [comment] 2020-06-15 20:27
No problem. Are you on the CEPGP discord? I'll need help testing fixes because I'm not experiencing the issue on my client.

**Comment by krutticus** [comment] 2020-06-16 13:43
I just joined the discord, I'll keep an eye out.  Feel free to contact me there if there's any way I can assist; I'll be under the same name.  I'm not sure if it'll remedy but we're going to try having less assists in raid this week's raid and see if there's any impact.

**Comment by Alumian** [comment] 2020-07-16 11:03
Hi Krut,

Please have your raid team download update 1.12.19 and test to see if the issue persists. Please let me know.

Thanks

**Comment by Alumian** [comment] 2020-07-27 10:34
Issue has been confirmed resolved in 1.12.20.

**Closed by Alumian** 2020-07-27 10:34 UTC
Labels: bug, fixed
