### ISSUE TITLE
More Loot Options [Request]

### ISSUE THREAD

**Issue by Fluuse** [Alumian/CEPGP-Retail#56] opened 2019-10-10 20:42 UTC
Hi, we heavily need 1 or 2 more buttons for Loot distribution, great would be
[BiS] [Need] [Offspec] [Pass], where you can set a different amount of GP cost to each button.
Even better would be freely customizable options.

**Comment by Alumian** [comment] 2019-10-10 20:48
Duplicate of https://github.com/Alumian/CEPGP-Retail/issues/23.

**Closed by Alumian** 2019-10-10 20:48 UTC
Labels: request
