### ISSUE TITLE
[Request] Add Verbose Logging option

### ISSUE THREAD

**Issue by HS-Disq** [Alumian/CEPGP-Retail#205] opened 2020-02-21 12:05 UTC
Hi,

Can we have an option in CEPGP to enable Verbose Logging? I really want to see which members received how much EP when mass EP is given to them.

Thanks.

**Comment by luozm** [comment] 2020-02-22 00:21
yea this is also what i want

**Comment by Alumian** [comment] 2020-07-16 11:49
Duplicate of #173

**Closed by Alumian** 2020-07-16 11:49 UTC
Labels: duplicate, request
