### ISSUE TITLE
[Bug] Players in the raid whispering !need are not appearing in the distribution list

### ISSUE THREAD

**Issue by mykkenny** [Alumian/CEPGP-Retail#51] opened 2019-10-08 22:30 UTC
**The Error**
No error.

**Describe the bug**
When players would whisper me (the master looter) `!need` they would not appear in the distribution list. See screenshot:

https://i.imgur.com/Yrjcm6G.jpg

**To Reproduce**
Unsure - didn't really want to try to reproduce it! Happened three times throughout the night though, pretty much for every loot distribution. Pretty consistent.

**Debug Information**
<details><summary>Debug Info</summary><br />Version: 1.12.0<br /><br />GP Modifier: 10<br /><br />Base GP: 1<br /><br />Standby EP: True<br /><br />Standby Offline: True<br /><br />Standby Percent: 100<br /><br />Standby Accept Whispers: True<br /><br />Standby EP by Rank: False<br /><br />Standby EP Manual Delegation: True<br /><br />GUI for Loot: False<br /><br />Loot Response Keyphrase: !need<br /><br />Standby EP Whisper Keyphrase: standby<br /><br /><details><summary>Auto EP</summary>High Priestess Jeklik: True<br />Gothik the Harvester: True<br />Buru the Gorger: True<br />Wushoolay: True<br />Lord Kri: True<br />Emperor Vek'nilash: True<br />Ossirian the Unscarred: True<br />Golemagg the Incinerator: False<br />Grand Widow Faerlina: True<br />High Priestess Mar'li: True<br />Majordomo Executus: False<br />High Priest Venoxis: True<br />Gehennas: False<br />Taerar: True<br />Ysondre: True<br />Thane Korth'azz: True<br />High Priest Thekal: True<br />Noth the Plaguebringer: True<br />Lethon: True<br />Moam: True<br />The Prophet Skeram: True<br />Flamegor: True<br />C'Thun: True<br />General Rajaxx: True<br />Princess Huhuran: True<br />Thaddius: True<br />Loatheb: True<br />Lady Blaumeux: True<br />Highlord Mograine: True<br />Heigan the Unclean: True<br />Azuregos: True<br />Doom Lord Kazzak: True<br />Teremus the Devourer: True<br />Jin'do the Hexxer: True<br />Baron Geddon: False<br />Renataki: True<br />Sulfuron Harbinger: False<br />Gri'lek: True<br />Bloodlord Mandokir: True<br />Patchwerk: True<br />Vaelastrasz the Corrupt: True<br />Gluth: True<br />Sapphiron: True<br />Emeriss: True<br />Onyxia: False<br />Princess Yauj: True<br />Kurinnaxx: True<br />Shazzrah: False<br />Ebonroc: True<br />Battleguard Sartura: True<br />Hakkar: True<br />Kel'Thuzad: True<br />Nefarian: True<br />Fankriss the Unyielding: True<br />Lucifron: False<br />Anub'Rekhan: True<br />Hazza'rah: True<br />Viscidus: True<br />Broodlord Lashlayer: True<br />Ayamiss the Hunter: True<br />Ragnaros: False<br />Maexxna: True<br />Ouro: True<br />Vem: True<br />Grobbulus: True<br />Instructor Razuvious: True<br />Razorgore the Untamed: True<br />Magmadar: False<br />Sir Zeliek: True<br />Gahz'ranka: True<br />Emperor Vek'lor: True<br />High Priestess Arlokk: True<br />Firemaw: True<br />Chromaggus: True<br />Garr: False<br /></details><br /><details><summary>EP Values</summary>High Priestess Jeklik: 2<br />Gothik the Harvester: 12<br />Buru the Gorger: 3<br />Wushoolay: 2<br />Lord Kri: 10<br />Emperor Vek'nilash: 10<br />Ossirian the Unscarred: 4<br />Golemagg the Incinerator: 5<br />Grand Widow Faerlina: 12<br />High Priestess Mar'li: 2<br />Majordomo Executus: 5<br />High Priest Venoxis: 2<br />Gehennas: 5<br />Taerar: 7<br />Ysondre: 7<br />Thane Korth'azz: 15<br />High Priest Thekal: 2<br />Noth the Plaguebringer: 12<br />Lethon: 7<br />Moam: 3<br />The Prophet Skeram: 10<br />Flamegor: 7<br />C'Thun: 12<br />General Rajaxx: 3<br />Princess Huhuran: 10<br />Thaddius: 15<br />Loatheb: 15<br />Lady Blaumeux: 15<br />Highlord Mograine: 15<br />Heigan the Unclean: 12<br />Azuregos: 7<br />Doom Lord Kazzak: 7<br />Teremus the Devourer: 7<br />Jin'do the Hexxer: 2<br />Baron Geddon: 5<br />Renataki: 2<br />Sulfuron Harbinger: 5<br />Gri'lek: 2<br />Bloodlord Mandokir: 2<br />Patchwerk: 12<br />Vaelastrasz the Corrupt: 7<br />Gluth: 12<br />Sapphiron: 15<br />Emeriss: 7<br />Onyxia: 5<br />Princess Yauj: 10<br />Kurinnaxx: 3<br />Shazzrah: 5<br />Ebonroc: 7<br />Battleguard Sartura: 10<br />Hakkar: 3<br />Kel'Thuzad: 15<br />Nefarian: 10<br />Fankriss the Unyielding: 10<br />Lucifron: 5<br />Anub'Rekhan: 12<br />Hazza'rah: 2<br />Viscidus: 10<br />Broodlord Lashlayer: 7<br />Ayamiss the Hunter: 3<br />Ragnaros: 7<br />Maexxna: 15<br />Ouro: 10<br />Vem: 10<br />Grobbulus: 12<br />Instructor Razuvious: 12<br />Razorgore the Untamed: 7<br />Magmadar: 5<br />Sir Zeliek: 15<br />Gahz'ranka: 2<br />Emperor Vek'lor: 10<br />High Priestess Arlokk: 2<br />Firemaw: 7<br />Chromaggus: 7<br />Garr: 5<br /></details><br /><details><summary>Standby Guild Ranks</summary>Guild Master: False<br />Officer: False<br />Officer Alt: False<br />Raider: False<br />Member: False<br />Alt: False<br />Social Rank: False<br />Trial: False<br />Noob: False<br /></details><br /><details><summary>Slot Weights</summary>2HWEAPON: 2<br />NECK: 0.5<br />HEAD: 1<br />WEAPON: 1.5<br />WRIST: 0.5<br />WEAPONMAINHAND: 1.5<br />SHIELD: 0.5<br />HOLDABLE: 0.5<br />RANGED: 0.5<br />THROWN: 0.5<br />FEET: 0.75<br />RELIC: 0.5<br />RANGEDRIGHT: 0.5<br />WEAPONOFFHAND: 0.5<br />TRINKET: 0.75<br />FINGER: 0.5<br />CLOAK: 0.5<br />CHEST: 1<br />ROBE: 1<br />HAND: 0.75<br />WAIST: 0.75<br />EXCEPTION: 1<br />LEGS: 1<br />SHOULDER: 0.75<br /></details><br /><details><summary>Override List</summary></details><br /><details><summary>Addons List</summary><br />Atlas<br />Atlas_ClassicWoW<br />AtlasLootClassic<br />Auctionator<br />BetterVendorPrice<br />CEPGP<br />Clique<br />GigaAutoResourcesTracker<br />ItemTooltipProfessionIcons<br />Kui_Media<br />Kui_Nameplates<br />Kui_Nameplates_Core<br />Leatrix_Maps<br />Leatrix_Plus<br />Peggle<br />QuestLogEx<br />RealMobHealth<br />RecipeRadarClassic<br />Recount<br />TriviaBot<br />WhatsTraining<br />CharacterStatsClassic<br />ProjectAzilroka<br />AddOnSkins<br />ElvUI_BenikUI_Classic<br />ElvUI<br />DBM-Core<br />DBM-DefaultSkin<br />DBM-StatusBarTimers<br />Questie<br /></details></details>

**Comment by Alumian** [comment] 2019-10-08 23:02
Looks as though either the frame isn't update frequently enough or like your other ticket, a desynchronisation has occurred. I'll look into this.

**Comment by mykkenny** [comment] 2019-10-08 23:06
I waited a few minutes a couple of times, asked people to whisper `!need` again, no joy.

**Comment by Alumian** [comment] 2019-10-08 23:15
Hmm.. Okay I'll look into this and get back to you. Unfortunately I won't be able to check this out until I get home this afternoon which is in about 6-7 hours roughly.

**Comment by PibbzTV** [comment] 2019-10-09 18:11
I get this today aswelll. Really really disastrous :(

**Comment by Alumian** [comment] 2019-10-10 03:01
I'm sorry about the disruption Pibbz, I'm working on this issue but it's proving to be a bit of a tough one to work out. I observed this issue in my guild's raid last night but curiously enough, it only occurred for one player and they confirmed that they're running the addon. Same version and all that, but for some reason, despite relogging, they were showing up in my version frame as "Addon not enabled". Worked just fine for everyone else. I'm going to troubleshoot this further with him this afternoon. At this stage, I highly doubt it's a desynhronisation issue.

**Comment by mykkenny** [comment] 2019-10-10 07:22
It's interesting that when a player whispers me `!need` the addon *always* without fail acknowledges this by outputting into the designated channel that 'player X needs' and their PR score, but then it fails to add them to the distribution list. You can see this in the screenshot in my initial report. So feels like there is a break with adding them to the distribution list?

**Comment by PibbzTV** [comment] 2019-10-10 08:03
My guess is that it's related to the new "Enable GUI for Loot" feature in some way or another.

**Comment by PibbzTV** [comment] 2019-10-10 08:04
Thats a synced reply if I ever saw one :D

**Comment by Alumian** [comment] 2019-10-10 08:04
> My guess is that it's related to the new "Enable GUI for Loot" feature in some way or another.

This is not related to that feature. I implemented that feature and this was working at the time.

**Comment by PibbzTV** [comment] 2019-10-10 08:05
> 
> 
> > My guess is that it's related to the new "Enable GUI for Loot" feature in some way or another.
> 
> This is not related to that feature. I implemented that feature and this was working at the time.

Allright, perfect! :)

**Comment by Alumian** [comment] 2019-10-10 08:15
Ooooooooooooookay. So I just gave my guildy a fresh copy of the addon, told him to rename his old one and to install this one. He is now getting the notice frame, his version can be detected and he is now showing up on the loot frame. I genuinely have no idea what went wrong.

**Comment by Alumian** [comment] 2019-10-10 08:18
Could you uhh, could you try getting your affected guildies to redownload the addon and to delete their old version and let me know if the issue persists?

**Comment by Alumian** [comment] 2019-10-10 08:23
@PibbzTV you as well please.

**Comment by mykkenny** [comment] 2019-10-10 08:28
Next raid is Sunday but I'll try to do something tonight in a dungeon or something. There are definitely people running the old addon version, so I will try to grab one who has the latest and one who has an out of date version.

My only question is, surely it only matters that I am up to date? Once I receive the whisper isn't all the work of adding the player to the distribution list done by my (up to date) addon? There is no further interaction between our addons? 

We're not using the GUI for looting btw, people just whisper !need thats it. Not everyone has it installed.

**Comment by PibbzTV** [comment] 2019-10-10 08:47
Next raid is Sunday for us aswell. I still have to manually update the entire guilds EP and GP after yesterdays dual MC raid before I can test this. But sure, I'll get the latest version. We don't use the GUI for loot distribution either, just the !need whisper.

**Comment by Alumian** [comment] 2019-10-10 09:46
You can test on anything actually. Anything that isn't currency. All you need to do is, while in a raid group, type /cep debugmode, open loot window for a creature and you'll be able to hit announce and check the window and all that. Even on grey items, you just won't be able to distribute them which is fine.

**Comment by askthedragon** [comment] 2019-10-10 12:15
I am experiencing the exact same issue as described.  Players will whisper !need and they do not show up in the distribution list.  No one else in the guild was using the addon at the time.  I was using the latest in master as of last night.  I'll try testing the addon some more as you described.  This issue happened during every boss in MC.

**Comment by askthedragon** [comment] 2019-10-10 12:18
I wanted to add that /cep version shows 1.12.2

**Comment by Alumian** [comment] 2019-10-10 12:25
Okay and you're sure no one else has the add-on? If that's the case I feel like I might have missed that when I was rebuilding the loot table. I'll look into this.

**Comment by Alumian** [comment] 2019-10-11 00:04
Alright it looks like this is actually two completely separate issues. So the issues here are:

1. For some clients, the addon is not actually "starting", i.e. the "ADDON_LOADED" event is not firing. Implications are saved variables and global variables don't load and the listeners never start. The problem there is, the client receives addon messages, but it's not listening/responding to them. 

2. I simply forgot to add in the section for when people aren't running the addon.

**Comment by askthedragon** [comment] 2019-10-11 00:38
Answering your prior question.  I'm 100% sure I was the only one with the addon during raid.

For case 1 above, I can test to see if my ADDON_LOADED event handler is firing and report back.

**Comment by Alumian** [comment] 2019-10-11 00:40
Okay thanks. Essentially you can tell if you go /cep version and you can see your own version number. My guildy had this problem and at the top where it's supposed to say "Current Version 1.12.2", the whole fontstring was blank. I checked his /etrace and nothing was coming through.

**Comment by PibbzTV** [comment] 2019-10-11 08:37
So this should eliminate the need for everyone to have the addon installed again? Masterlooter is enough? :)

**Comment by Alumian** [comment] 2019-10-11 08:38
It -should-. That was the case when I tested it this afternoon. There was a player without the add-on installed and they showed up on my frame.

**Comment by mykkenny** [comment] 2019-10-13 22:24
Okay, downloaded 1.12.3-beta, and had no issues at all tonight. Everyone who whispered appeared in the list. Some had the addon (1.12) and some did not. So looks good to me!

**Comment by Alumian** [comment] 2019-10-13 22:27
Fantastic, great to hear. I've also received the same feedback from others who have used 1.12.3 so I'll go ahead and close this ticket.
By the way, I've started up a CEPGP discussion discord if you were interested in joining: https://discord.gg/7mG4GAr
Kinda just trialing it at the moment to see how manageable it is, but we'll see how we go.

**Closed by Alumian** 2019-10-13 22:27 UTC
Labels: bug

**Comment by PibbzTV** [comment] 2019-10-15 06:44
No bugs detected in our sunday raids either. Looking great! :)
