### ISSUE TITLE
[Request] Introduce the possibility to put items from the bag into the system

### ISSUE THREAD

**Issue by bijngo** [Alumian/CEPGP-Retail#258] opened 2020-05-11 14:10 UTC
It would be really helpful if the masterlooteror or any other person in the raid could also introduce items out of the bag into the distribution system. so you could distribute way easier if you do not distirbute during the run/directly after a bossfight.

**Comment by Alumian** [comment] 2020-05-16 22:40
Duplicate of #228

**Closed by Alumian** 2020-05-16 22:40 UTC
Labels: duplicate, request
