### ISSUE TITLE
[Question] Ineligible for Loot

### ISSUE THREAD

**Issue by synatk** [Alumian/CEPGP-Retail#80] opened 2019-10-20 21:38 UTC
Hey,

First, thank you for the Port of this add-on. Second, I have a question about 'Ineligibility' for loot when the loot box pops up to raid members.  For an example; we had a paladin win the lawbringer gloves earlier in a raid.  We get to Golemagg and the Azure MageBlade drops - the loot box said the person was ineligible to roll. The pass button was the only button clickable even though the person could equip the item.  Is this a setting in the addon? What would make the person ineligible and the loot box give the pass only option? Their 'Automatically pass on unusable items' setting? Or their PR was not high enough against all that were eligible? Should they be able to click the Main Spec need button even if there was no chance of winning?

Thanks!

**Comment by Alumian** [comment] 2019-10-20 21:51
Hey,
Just to clarify, this isn't a port lol. I just need to clarify, when you say they were ineligible for loot - was that saying it on your end or on their end?
If it was saying it on your end, then that means that player didn't participate in the encounter and that means that the actual blizzard interface is preventing it. If the issue is occurring on their end where they can only see a pass button when using the loot GUI....I don't know. The main spec button is hard coded into the frame so I don't know why that would happen.

**Comment by synatk** [comment] 2019-10-20 22:09
Clarification noted. This was on their end, not the ML end.

**Comment by Alumian** [comment] 2019-10-20 22:59
Hmmmm.. id need to know a little bit more definitively what the behaviour is. Because if the loot GUI wasn't appearing at all then that would likely be down to the auto pass function playing up (assuming they have that enabled). Would you be able to find out for me if the loot GUI is appearing?

**Comment by Alumian** [comment] 2019-10-25 13:12
Closing as no further response has been received.

**Closed by Alumian** 2019-10-25 13:12 UTC
Labels: question
