### ISSUE TITLE
[Request] possibility to start loot distribution out of corpse

### ISSUE THREAD

**Issue by thowt** [Alumian/CEPGP-Retail#247] opened 2020-04-17 12:20 UTC
Possibility to start loot distribution out of corpse, eg. on item from bag.
Eg:
Starting with ZG, we are changing loot distribution between trash and bosses. If we forget to change to ML before boss encounter and everyone will pass the loot, we are not able to start distribution via CEPGP. 

So some manual command, button, whatever to start the distribution of provided item in raid like during ML.

TY

**Comment by Alumian** [comment] 2020-04-17 12:22
Duplicate of ticket #228. Please see that ticket for updates on this request.

**Closed by Alumian** 2020-04-17 12:22 UTC
Labels: duplicate, request
