### ISSUE TITLE
[Bug] Raid ID/Locks and wrong guild mate getting EP

### ISSUE THREAD

**Issue by jackie0100** [Alumian/CEPGP-Retail#61] opened 2019-10-14 00:50 UTC
**The Error**
None

**Describe the bug**
Hey I noticed today that somehow wrong people had gotten EP from our raid, it seems some of them were from the same instance-ID however we/I did also have a odd one as an alt which join the guild doing the raid, had randomly gotten EPs as if he had been part of the raid, although he wasn't in the raid. I was wondering if there is anything I may have been doing wrong, or if this maybe more would categories as a bug as it seemed some people in the raid DID NOT earn any EPs (some of the people did join in after the initial raid start) but some who were not in the raid, but were in the guild DID earn EPs.

a little programmer talk;
I'm not sure if the guild names etc is indexed before hand so the index may come out of sync as a new person join the guild, and there by award the people wrong?

Regardless I'll keep an eye open if this happens again next raid and come back if more weirdness is happening. 

**To Reproduce**
Not sure but I'll keep ya posted

**Debug Information**
<details><summary>Debug Info</summary><br />Version: 1.12.3<br /><br />GP Modifier: 1<br /><br />Base GP: 100<br /><br />Standby EP: False<br /><br />Standby Offline: False<br /><br />Standby Percent: 0<br /><br />Standby Accept Whispers: False<br /><br />Standby EP by Rank: True<br /><br />Standby EP Manual Delegation: False<br /><br />GUI for Loot: False<br /><br />Loot Response Keyphrase: !need<br /><br />Standby EP Whisper Keyphrase: standby<br /><br /><details><summary>Auto EP</summary>High Priestess Jeklik: True<br />Gothik the Harvester: True<br />Buru the Gorger: True<br />Wushoolay: True<br />Lord Kri: True<br />Emperor Vek'nilash: True<br />Ossirian the Unscarred: True<br />Golemagg the Incinerator: True<br />Grand Widow Faerlina: True<br />High Priestess Mar'li: True<br />Majordomo Executus: True<br />High Priest Venoxis: True<br />Gehennas: True<br />Taerar: True<br />Ysondre: True<br />Thane Korth'azz: True<br />High Priest Thekal: True<br />Noth the Plaguebringer: True<br />Lethon: True<br />Moam: True<br />The Prophet Skeram: True<br />Flamegor: True<br />C'Thun: True<br />General Rajaxx: True<br />Princess Huhuran: True<br />Thaddius: True<br />Loatheb: True<br />Lady Blaumeux: True<br />Highlord Mograine: True<br />Heigan the Unclean: True<br />Azuregos: True<br />Doom Lord Kazzak: True<br />Teremus the Devourer: True<br />Jin'do the Hexxer: True<br />Baron Geddon: True<br />Renataki: True<br />Sulfuron Harbinger: True<br />Gri'lek: True<br />Bloodlord Mandokir: True<br />Patchwerk: True<br />Vaelastrasz the Corrupt: True<br />Gluth: True<br />Sapphiron: True<br />Emeriss: True<br />Onyxia: True<br />Princess Yauj: True<br />Kurinnaxx: True<br />Shazzrah: True<br />Ebonroc: True<br />Battleguard Sartura: True<br />Hakkar: True<br />Kel'Thuzad: True<br />Nefarian: True<br />Fankriss the Unyielding: True<br />Lucifron: True<br />Anub'Rekhan: True<br />Hazza'rah: True<br />Viscidus: True<br />Broodlord Lashlayer: True<br />Ayamiss the Hunter: True<br />Ragnaros: True<br />Maexxna: True<br />Ouro: True<br />Vem: True<br />Grobbulus: True<br />Instructor Razuvious: True<br />Razorgore the Untamed: True<br />Magmadar: True<br />Sir Zeliek: True<br />Gahz'ranka: True<br />Emperor Vek'lor: True<br />High Priestess Arlokk: True<br />Firemaw: True<br />Chromaggus: True<br />Garr: True<br /></details><br /><details><summary>EP Values</summary>High Priestess Jeklik: 2<br />Gothik the Harvester: 12<br />Buru the Gorger: 3<br />Wushoolay: 2<br />Lord Kri: 10<br />Emperor Vek'nilash: 10<br />Ossirian the Unscarred: 4<br />Golemagg the Incinerator: 5<br />Grand Widow Faerlina: 12<br />High Priestess Mar'li: 2<br />Majordomo Executus: 5<br />High Priest Venoxis: 2<br />Gehennas: 5<br />Taerar: 7<br />Ysondre: 7<br />Thane Korth'azz: 15<br />High Priest Thekal: 2<br />Noth the Plaguebringer: 12<br />Lethon: 7<br />Moam: 3<br />The Prophet Skeram: 10<br />Flamegor: 7<br />C'Thun: 12<br />General Rajaxx: 3<br />Princess Huhuran: 10<br />Thaddius: 15<br />Loatheb: 15<br />Lady Blaumeux: 15<br />Highlord Mograine: 15<br />Heigan the Unclean: 12<br />Azuregos: 7<br />Doom Lord Kazzak: 7<br />Teremus the Devourer: 7<br />Jin'do the Hexxer: 2<br />Baron Geddon: 5<br />Renataki: 2<br />Sulfuron Harbinger: 5<br />Gri'lek: 2<br />Bloodlord Mandokir: 2<br />Patchwerk: 12<br />Vaelastrasz the Corrupt: 7<br />Gluth: 12<br />Sapphiron: 15<br />Emeriss: 7<br />Onyxia: 5<br />Princess Yauj: 10<br />Kurinnaxx: 3<br />Shazzrah: 5<br />Ebonroc: 7<br />Battleguard Sartura: 10<br />Hakkar: 3<br />Kel'Thuzad: 15<br />Nefarian: 10<br />Fankriss the Unyielding: 10<br />Lucifron: 5<br />Anub'Rekhan: 12<br />Hazza'rah: 2<br />Viscidus: 10<br />Broodlord Lashlayer: 7<br />Ayamiss the Hunter: 3<br />Ragnaros: 7<br />Maexxna: 15<br />Ouro: 10<br />Vem: 10<br />Grobbulus: 12<br />Instructor Razuvious: 12<br />Razorgore the Untamed: 7<br />Magmadar: 5<br />Sir Zeliek: 15<br />Gahz'ranka: 2<br />Emperor Vek'lor: 10<br />High Priestess Arlokk: 2<br />Firemaw: 7<br />Chromaggus: 7<br />Garr: 5<br /></details><br /><details><summary>Standby Guild Ranks</summary>Guildmaster: False<br />Officer: False<br />Guild Mascot: False<br />Officer Alt: False<br />Oldtimer: False<br />Raider: False<br />Trial Raider: False<br />Member: False<br />Alt char: False<br />Recruit: False<br /></details><br /><details><summary>Slot Weights</summary>2HWEAPON: 2<br />NECK: 0.5<br />HEAD: 1<br />WEAPON: 1.5<br />WRIST: 0.5<br />WEAPONMAINHAND: 1.5<br />SHIELD: 0.5<br />HOLDABLE: 0.5<br />RANGED: 0.5<br />THROWN: 0.5<br />FEET: 0.75<br />RELIC: 0.5<br />RANGEDRIGHT: 0.5<br />WEAPONOFFHAND: 0.5<br />TRINKET: 0.75<br />FINGER: 0.5<br />CLOAK: 0.5<br />CHEST: 1<br />ROBE: 1<br />HAND: 0.75<br />WAIST: 0.75<br />EXCEPTION: 1<br />LEGS: 1<br />SHOULDER: 0.75<br /></details><br /><details><summary>Override List</summary></details><br /><details><summary>Addons List</summary><br />Atlas<br />Atlas_ClassicWoW<br />AtlasLootClassic<br />Auc-Advanced<br />Auc-Filter-Basic<br />Auc-Stat-Histogram<br />Auc-Stat-iLevel<br />Auc-Stat-Purchased<br />Auc-Stat-Simple<br />Auc-Stat-StdDev<br />Auc-Util-FixAH<br />Auctionator<br />auc-cheap-searcher<br />Bagnon<br />Bartender4<br />BeanCounter<br />CEPGP<br />ClassicCastbars<br />ClassicCastbars_Options<br />ClassicThreatMeter<br />CT_BuffMod<br />CT_Core<br />CT_ExpenseHistory<br />CT_Library<br />CT_Timer<br />Decursive<br />Details<br />Details_TinyThreat<br />Dismounter<br />ExRT<br />ExtendedCharacterStats<br />GatherLite<br />Get Spheres - Classic<br />InFlight_Load<br />JumpCounter<br />Mapster<br />MarketWatcher<br />MobInfo2-Classic<br />OmniCC<br />Peggle<br />Prat-3.0<br />Prat-3.0_Libraries<br />QuestCompletist<br />RareAware<br />Scrap<br />Scrap_Spotlight<br />SexyMap<br />SilverRareElites<br />SilverDragon<br />SilverDragon_Classic<br />SlideBar<br />Stubby<br />!Swatter<br />TitanAttributesMulti<br />TitanProfessionsMulti<br />TitanClassicReagentTracker<br />TitanReputations<br />TitanClassicAmmo<br />TitanClassicBag<br />TitanClassicClock<br />TitanClassicGold<br />TitanClassicLocation<br />TitanClassicLootType<br />TitanClassicPerformance<br />TitanClassicRegen<br />TitanClassicRepair<br />TitanClassicVolume<br />TitanClassicXP<br />TitanClassic<br />TriviaBot<br />WeakAuras<br />ZPerl<br />ZPerl_ArcaneBar<br />ZPerl_PartyPet<br />ZPerl_Party<br />ZPerl_PlayerBuffs<br />ZPerl_PlayerPet<br />ZPerl_Player<br />ZPerl_RaidAdmin<br />ZPerl_RaidFrames<br />ZPerl_RaidHelper<br />ZPerl_RaidPets<br />ZPerl_TargetTarget<br />ZPerl_Target<br />DBM-Core<br />DBM-DefaultSkin<br />DBM-StatusBarTimers<br />Questie<br /></details></details>

**Comment by Alumian** [comment] 2019-10-14 01:01
Hmm, that's odd. There was a bug previously exactly as you described in version 1.12.0 but it was fixed in 1.12.2. The guild roster is updated in CEPGP periodically, but also it is updated any time a change is made to a guild member. Similarly, the raid roster in CEPGP is updated any time a change is made to the raid (such as players joining/leaving or moving groups).
Are you certain that you were running version 1.12.3 at the time that this happened? I haven't received any other reports of this on this version.

**Comment by jackie0100** [comment] 2019-10-16 07:22
I'm at this point very uncertain if I was on 1.12.0 or 1.12.2, however, I am now on 1.12.3 and will be raiding to night and I will be back with further information

**Comment by jackie0100** [comment] 2019-10-16 22:02
Seems to be working completely fine today with 1.12.3

I did however notice a few other things to day,

1: The EPGP Formula seems broken or uses some non-standard math logics I've made a "cheat sheet" here; https://docs.google.com/spreadsheets/d/1QRQWi7TSdlRa1ZlKKv9Vt9uOiBLHe-ke-7kcwcZ9JL4 (Ark one) and a piece which should be worth 5 GP showed up as only being worth 1 GP for some reason - Is there anyways you can explain that formula to me?

2: I noticed that as a mage I could roll/need on Warlock and priest tier 1, and I also had the ability to roll on brutality blade (this one I kinda  understand why tho)

3: In the loot window when trying to sort by priority it seems that it wrong sorts the PR


with these small bugs mentioned - Thanks for the support and mod, you're doing an amazing job with this on for sure! :)

**Comment by Alumian** [comment] 2019-10-16 22:12
1. Because I was a dumbass and screwed up the default formula, so I do recommend you change that. If you keep it as 4.83x(**1** then the item level makes no difference.

2. No idea, I'll look into it.

3. That's wierd. I'll look into that too.

I'm going to release a new version fairly soon so that might fix some of the bugs you're experiencing. For the time being though, since you've confirmed that this issue has been resolved, I'm going to close this ticket.
Thanks!

**Closed by Alumian** 2019-10-16 22:12 UTC
Labels: bug
