### ISSUE TITLE
[Bug]EPGP decay

### ISSUE THREAD

**Issue by Naniq** [Alumian/CEPGP-Retail#114] opened 2019-10-31 15:37 UTC
**Describe the bug**
Once every week I wanna do a decay of the EP, I know that it takes in the GP aswell but this seems buggy.

I add in 25% of decay.
Some players reset down to 0 EP, even though they have maybe 200 EP, also if someone has 103 GP as an example (We have a starting value of everyone at 100)
They go down to just 100 GP instead of decaying also with 25%
Some players do however reset correctly in EP and loses the 25%, but atleast 5-7 are not and are just reset to 0

**Comment by Alumian** [comment] 2019-10-31 19:01
Duplicate of #112.

**Closed by Alumian** 2019-10-31 19:01 UTC
Labels: bug, duplicate
