### ISSUE TITLE
[Bug] Guild Standings screen assumes Base GP is lowest possible GP value

### ISSUE THREAD

**Issue by Anilusion** [Alumian/CEPGP-Retail#248] opened 2020-04-17 14:04 UTC
![base gp bug](https://user-images.githubusercontent.com/9070713/79577537-2839a300-80c5-11ea-89df-5b78053d73e6.jpg)

**Describe the bug**
I have characters in 2 different guilds, both of which are using CEPGP for loot. In one of the guilds I am managing the system, in the other guild I'm just a raider with no authority. Because of this, I need my CEPGP settings to always match those of my main guild (as there are no character specific settings). My main guild and my alt guild have different Base GP values, and previously this has not been an issue. But now the Guild Standings screen assumes that the base GP in settings is the lowest GP possible, meaning that everyone below 150 GP will be displayed (and their PR will be calculated as if) their GP was 150.

**To Reproduce**
Be in a guild with people who have lower GP than you have Base GP set to in your own settings.

**Debug Information**
https://pastebin.com/vnvPkkDY - Uploaded to pastebin as it is close to 1000 lines.

**Comment by Alumian** [comment] 2020-04-17 14:26
Hi @Anilusion,
This is intended behaviour. It is a mask as opposed to aggressively making changes as it finds the GP values are too low. There is intention to add character (or maybe even guild specific) settings. Still trying to work out the implementation on that one. But yeah, in terms of this report, this is intended behaviour so I'm going to close this for now.
Also just a quick note - don't worry about how many lines the debug info is. I've formatted it specifically for GitHub so it actually turns into a series of expandable menus. I've edited your original post accordingly.

**Closed by Alumian** 2020-04-17 14:26 UTC
Labels: bug, wontfix

**Comment by Anilusion** [comment] 2020-04-17 14:29
Alright, that's understandable. Would you mind telling me the location of the code that populates the guild overview? Perhaps I can change it for myself locally until character specific settings are in.

**Comment by scarecr0w12** [comment] 2020-04-18 21:41
> Alright, that's understandable. Would you mind telling me the location of the code that populates the guild overview? Perhaps I can change it for myself locally until character-specific settings are in.

You can change the TOC area that specifies `SavedVariables` and change it to `SavedVariablesPerCharacter`

HOWEVER NOTE. Doing this resets the addon to ALL default settings. you can import however from another online character in your guild that has the settings. I've tested this myself. Though, and future updates will need the TOC file change.
