### ISSUE TITLE
[Bug]Lua error occurred when add ep/gp to members.

### ISSUE THREAD

**Issue by rxcxj77** [Alumian/CEPGP-Retail#201] opened 2020-02-17 01:47 UTC
**The Error**
What was the error message you received?
Message: Interface\AddOns\CEPGP\Utility.lua:2020: SendChatMessage(): Unknown chat type
Time: Mon Feb 17 09:36:05 2020
Count: 1
Stack: Interface\AddOns\CEPGP\Utility.lua:2020: SendChatMessage(): Unknown chat type
[C]: in function `SendChatMessage'
Interface\AddOns\CEPGP\Utility.lua:2020: in function `CEPGP_sendChatMessage'
Interface\AddOns\CEPGP\Core.lua:849: in function `CEPGP_addEP'
Interface\AddOns\CEPGP\Button.lua:245: in function <Interface\AddOns\CEPGP\Button.lua:238>

Locals: (*temporary) = "1 EP added to 韭菜青青 (测试)"
(*temporary) = "工会"
(*temporary) = nil

**Describe the bug**
/cep show
click guild and add ep/gp to members.
lua error occurred

**To Reproduce**
How can this bug be reproduced?
/cep show
click guild and add ep/gp to members.
lua error occurred

**Debug Information**
Type /cepgp debug and copy and paste the information into this bug report.
<details><summary>Debug Info</summary><br />
Version: 1.12.9 release<br />
Locale: zhCN<br />
GP Formula: (4.83x(1^<sup>((ilvl/26)+(rarity-4))</sup>)xSlot Modifier)x1<br />Base GP: 1<br />
Base GP Decay Factor: false<br />
Standby EP: False<br />
Standby Offline: False<br />
Standby Percent: 0<br />
Standby Accept Whispers: False<br />
Standby EP by Rank: True<br />
Standby EP Manual Delegation: False<br />
GUI for Loot: False<br />
Loot Response Keyphrase: !need<br />
Standby EP Whisper Keyphrase: standby<br />
Auto Pass on Ineligible Items: false<br />
Full Raid Loot Visibility: false<br />
GP on Tooltips: false<br />
Suppress Loot Announcements: false<br />
Minimum EP: false, 0<br />
Reporting Channel: 工会<br />
Loot Response Channel: 团队<br />
Minimum Threshold for Loot: 2<br />
Allow Force Sync: false, 合道<br />
<br /><details><summary>Auto EP</summary>
High Priestess Jeklik: True<br />
Gothik the Harvester: True<br />
Buru the Gorger: True<br />
Wushoolay: True<br />
管理者埃克索图斯: True<br />
Ossirian the Unscarred: True<br />
鲁西弗隆: True<br />
克洛玛古斯: True<br />
Golemagg the Incinerator: True<br />
Grand Widow Faerlina: True<br />
High Priestess Mar'li: True<br />
狂野的拉佐格尔: True<br />
Majordomo Executus: True<br />
Gahz'ranka: True<br />
加尔: True<br />
Gehennas: True<br />
Taerar: True<br />
Ysondre: True<br />
Thane Korth'azz: True<br />
沙斯拉尔: True<br />
Noth the Plaguebringer: True<br />
Lethon: True<br />
Renataki: True<br />
The Prophet Skeram: True<br />
Gluth: True<br />
C'Thun: True<br />
General Rajaxx: True<br />
Princess Huhuran: True<br />
焚化者古雷曼格: True<br />
Ragnaros: True<br />
奈法利安: True<br />
Thaddius: True<br />
Loatheb: True<br />
奥妮克希亚: True<br />
Ayamiss the Hunter: True<br />
Twin Emperors: True<br />
Jin'do the Hexxer: True<br />
Ebonroc: True<br />
堕落的瓦拉斯塔兹: True<br />
Sapphiron: True<br />
费尔默: True<br />
Heigan the Unclean: True<br />
High Priest Venoxis: True<br />
Onyxia: True<br />
Doom Lord Kazzak: True<br />
Firemaw: True<br />
萨弗隆先驱者: True<br />
勒什雷尔: True<br />
Vaelastrasz the Corrupt: True<br />
基赫纳斯: True<br />
Emeriss: True<br />
High Priestess Arlokk: True<br />
Gri'lek: True<br />
Baron Geddon: True<br />
迦顿男爵: True<br />
Kurinnaxx: True<br />
Bloodlord Mandokir: True<br />
Moam: True<br />
Maexxna: True<br />
Sulfuron Harbinger: True<br />
弗莱格尔: True<br />
High Priest Thekal: True<br />
Shazzrah: True<br />
Viscidus: True<br />
Battleguard Sartura: True<br />
Ouro: True<br />
Kel'Thuzad: True<br />
Nefarian: True<br />
Fankriss the Unyielding: True<br />
Lucifron: True<br />
Anub'Rekhan: True<br />
Hazza'rah: True<br />
Hakkar: True<br />
玛格曼达: True<br />
埃博诺克: True<br />
Azuregos: True<br />
Broodlord Lashlayer: True<br />
The Four Horsemen: True<br />
拉格纳罗斯: True<br />
Grobbulus: True<br />
Instructor Razuvious: True<br />
Razorgore the Untamed: True<br />
Magmadar: True<br />
Patchwerk: True<br />
Silithid Royalty: True<br />
Flamegor: True<br />
Chromaggus: True<br />
Garr: True<br />
</details>
<details><summary>EP Values</summary>
High Priestess Jeklik: 2<br />
Gothik the Harvester: 12<br />
Buru the Gorger: 3<br />
Wushoolay: 2<br />
管理者埃克索图斯: 8<br />
Ossirian the Unscarred: 4<br />
鲁西弗隆: 8<br />
克洛玛古斯: 7<br />
Golemagg the Incinerator: 8<br />
Grand Widow Faerlina: 12<br />
High Priestess Mar'li: 2<br />
狂野的拉佐格尔: 7<br />
Majordomo Executus: 8<br />
Gahz'ranka: 2<br />
加尔: 8<br />
Gehennas: 8<br />
Taerar: 7<br />
Ysondre: 7<br />
Thane Korth'azz: 15<br />
沙斯拉尔: 8<br />
Noth the Plaguebringer: 12<br />
Lethon: 7<br />
Renataki: 2<br />
The Prophet Skeram: 10<br />
Gluth: 12<br />
C'Thun: 12<br />
General Rajaxx: 3<br />
Princess Huhuran: 10<br />
焚化者古雷曼格: 8<br />
High Priest Venoxis: 2<br />
奈法利安: 10<br />
Thaddius: 15<br />
Loatheb: 15<br />
奥妮克希亚: 10<br />
Ayamiss the Hunter: 3<br />
Ragnaros: 8<br />
Jin'do the Hexxer: 2<br />
Silithid Royalty: 10<br />
Ebonroc: 15<br />
勒什雷尔: 7<br />
Twin Emperors: 10<br />
费尔默: 7<br />
Heigan the Unclean: 12<br />
Firemaw: 15<br />
Onyxia: 10<br />
Doom Lord Kazzak: 7<br />
Sapphiron: 15<br />
萨弗隆先驱者: 8<br />
Vaelastrasz the Corrupt: 15<br />
Emeriss: 7<br />
基赫纳斯: 8<br />
弗莱格尔: 7<br />
High Priestess Arlokk: 2<br />
Gri'lek: 2<br />
Kurinnaxx: 3<br />
迦顿男爵: 8<br />
Bloodlord Mandokir: 2<br />
Moam: 3<br />
Maexxna: 15<br />
Baron Geddon: 8<br />
Sulfuron Harbinger: 8<br />
High Priest Thekal: 2<br />
Viscidus: 10<br />
Lord Kazzak: 7<br />
Hakkar: 3<br />
Battleguard Sartura: 10<br />
Ouro: 10<br />
Kel'Thuzad: 15<br />
Nefarian: 15<br />
Fankriss the Unyielding: 10<br />
Lucifron: 8<br />
Anub'Rekhan: 12<br />
Hazza'rah: 2<br />
Shazzrah: 8<br />
玛格曼达: 8<br />
埃博诺克: 7<br />
Azuregos: 7<br />
Broodlord Lashlayer: 15<br />
The Four Horsemen: 15<br />
拉格纳罗斯: 8<br />
Grobbulus: 12<br />
Instructor Razuvious: 12<br />
Razorgore the Untamed: 15<br />
Magmadar: 8<br />
Patchwerk: 12<br />
堕落的瓦拉斯塔兹: 7<br />
Flamegor: 15<br />
Chromaggus: 15<br />
Garr: 8<br />
</details>
<details><summary>Standby Guild Ranks</summary>
合道: False<br />
EPGP管理: False<br />
职业队长: False<br />
拓荒团: False<br />
二团: False<br />
筑基: False<br />
小黑屋: False<br />
</details>
<details><summary>Slot Weights</summary>
2HWEAPON: 2<br />
NECK: 0.5<br />
HEAD: 1<br />
WEAPON: 1.5<br />
WRIST: 0.5<br />
WEAPONMAINHAND: 1.5<br />
SHIELD: 0.5<br />
HOLDABLE: 0.5<br />
CLOAK: 0.5<br />
FEET: 0.75<br />
THROWN: 0.5<br />
RELIC: 0.5<br />
RANGEDRIGHT: 0.5<br />
TRINKET: 0.75<br />
WEAPONOFFHAND: 0.5<br />
FINGER: 0.5<br />
CHEST: 1<br />
ROBE: 1<br />
HAND: 0.75<br />
WAIST: 0.75<br />
EXCEPTION: 1<br />
LEGS: 1<br />
SHOULDER: 0.75<br />
</details>
<details><summary>Override List</summary>
</details>
<details><summary>Addons List</summary>
CEPGP<br />
</details>
<details><summary>Enabled Plugins</summary>
</details>
</details>

**Comment by Alumian** [comment] 2020-02-19 19:27
Hey rxcxj77,

I believe I may have found the cause for this issue. To test, could you please do the following:
1. Type `/run SendChatMessage("Testing", "Guild", GetDefaultLanguage("player"));`
2. Type `/run SendChatMessage("Testing", "公会", GetDefaultLanguage("player"));

Please let me know which one of these works and which one gives you an error.

**Comment by rxcxj77** [comment] 2020-02-20 01:15
/run SendChatMessage("Testing", "Guild", GetDefaultLanguage("player"));  is good.

/run SendChatMessage("Testing", "公会", GetDefaultLanguage("player"));   is error.

**Comment by Alumian** [comment] 2020-02-20 01:21
Ok thanks, I'll have that fixed up for the next release.

**Comment by rxcxj77** [comment] 2020-02-20 01:21
OK~~

**Comment by rxcxj77** [comment] 2020-02-20 01:25
emm.
/cep show
guild translate should be '公会' not '工会'

**Comment by Alumian** [comment] 2020-02-22 22:54
Resolved in the next update.

**Comment by Alumian** [comment] 2020-04-11 06:03
Implementation has now been released.

**Closed by Alumian** 2020-04-11 06:03 UTC
Labels: bug, fixed
